export const guides = [
 {slug:"voice-and-perspective-extraction-coach", title:"get AI to actually sound like you.", fullTitle:"The voice extraction coach", description:"A coaching prompt that turns your perspective, stories and phrasing into a voice profile for AI.", category:"brand voice", cover:"your voice.\nnot robot voice.", theme:"pink", icon:"voice", date:"2026-08-19"},
 {slug:"repurpose-one-video-into-ten-posts", title:"one video. ten ways to use it.", fullTitle:"Repurpose one video into 10+ posts", description:"The Higgsfield + Claude workflow for turning one video into posts, carousels, emails and more.", category:"content", cover:"one video.\nten+ posts.", theme:"yellow", icon:"video", date:"2026-05-15"},
 {slug:"website-terms-explained-plain-english", title:"your website’s pretty. now what?", fullTitle:"15 website terms, explained in plain English", description:"SEO, site speed and the other things a pretty website needs, with a practical fix for each.", category:"websites", cover:"pretty is\nonly the start.", theme:"brown", icon:"website", date:"2026-09-09"},
 {slug:"automate-your-content-pipeline-with-ai", title:"give your content a system.", fullTitle:"Build an AI content pipeline", description:"Connect n8n, Apify, Claude, Notion and Buffer in a practical content automation workflow.", category:"automation", cover:"less copy.\nless paste.", theme:"yellow", icon:"systems", date:"2026-05-10"},
 {slug:"install-the-ig-competitor-research-skill", title:"know what’s working on Instagram.", fullTitle:"Install the IG competitor research skill", description:"Set up the Claude skill, connect Apify and run your first competitor research report.", category:"automation", cover:"research.\nthen create.", theme:"pink", icon:"systems", date:"2026-06-09"},
 {slug:"find-your-brand-voice", title:"find your voice. keep your voice.", fullTitle:"How to find your brand voice", description:"Define a recognizable voice and turn it into a skill file you can hand to your AI tools.", category:"brand voice", cover:"more you.\nevery time.", theme:"paper", icon:"voice", date:"2026-05-28"},
 {slug:"brand-identity-checklist-for-creators", title:"before you send that brand pitch…", fullTitle:"The brand identity checklist for creators", description:"A 12-point checklist to get your identity, presence and pitch materials in order.", category:"brand voice", cover:"ready for\nthe pitch.", theme:"pink", icon:"voice", date:"2026-05-01"},
 {slug:"wwdc-2026-business-owners-translation-guide", title:"Apple updates, in business language.", fullTitle:"WWDC 2026: the business owner’s translation guide", description:"Varnika’s guide to Apple’s 2026 announcements and what they mean for business discovery.", category:"websites", cover:"tech speak,\ntranslated.", theme:"paper", icon:"website", date:"2026-06-10"},
];
export type Guide = (typeof guides)[number];
export const guideUrl=(slug:string)=>"/guides/"+slug;
