// Prerender the vinext site to a static `out/` directory that any static host
// (Vercel, Netlify, GitHub Pages, Cloudflare Pages) can serve. The site has no
// server APIs or DB, uses plain <a> navigation, and inlines its RSC payload, so
// a fully-rendered HTML snapshot per route hydrates and works on its own.
//
// Runs the built Worker locally via wrangler (miniflare, no Cloudflare account),
// crawls every route, and copies the client assets alongside.

import { spawn } from "node:child_process";
import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const PORT = process.env.PRERENDER_PORT || "8799";
const BASE = `http://127.0.0.1:${PORT}`;
const root = process.cwd();
const outDir = resolve(root, "out");

// Free guide slugs (stable; must match lib/guides.ts). Detail routes are pushed below.
const GUIDE_SLUGS = [
  "voice-and-perspective-extraction-coach",
  "repurpose-one-video-into-ten-posts",
  "website-terms-explained-plain-english",
  "automate-your-content-pipeline-with-ai",
  "install-the-ig-competitor-research-skill",
  "find-your-brand-voice",
  "brand-identity-checklist-for-creators",
  "wwdc-2026-business-owners-translation-guide",
];

// HTML pages to snapshot.
const HTML_ROUTES = [
  "/", "/work-with-me", "/ai-systems", "/content-done", "/builds",
  "/mentorship", "/about", "/contact", "/partnerships",
  "/guides",
  ...GUIDE_SLUGS.map((slug) => "/guides/" + slug),
];
// Dynamic text routes (generated by app/sitemap.ts, app/robots.ts).
const TEXT_ROUTES = [
  ["/sitemap.xml", "sitemap.xml"],
  ["/robots.txt", "robots.txt"],
];

function log(m) { console.log(`[prerender] ${m}`); }

async function waitForServer(timeoutMs = 60000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    try {
      const r = await fetch(BASE + "/", { redirect: "manual" });
      if (r.status && r.status < 500) return true;
    } catch { /* not ready */ }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error("worker did not become ready in time");
}

async function saveRoute(path, filePath) {
  const res = await fetch(BASE + path);
  if (!res.ok) throw new Error(`route ${path} returned ${res.status}`);
  const body = await res.text();
  const dest = resolve(outDir, filePath);
  await mkdir(dirname(dest), { recursive: true });
  await writeFile(dest, body);
  return body.length;
}

let child;
try {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  // 1) copy built client assets (_next, assets, fonts, favicon, llms.txt, _headers)
  await cp(resolve(root, "dist/client"), outDir, { recursive: true });
  log("copied dist/client -> out");

  // 2) start the built worker locally (miniflare; no Cloudflare auth)
  log(`starting worker on :${PORT} ...`);
  child = spawn(
    "node",
    [
      "./node_modules/wrangler/bin/wrangler.js", "dev",
      "--config", "dist/server/wrangler.json",
      "--local", "--ip", "127.0.0.1", "--port", PORT, "--inspector-port", "0",
    ],
    { cwd: root, stdio: "ignore", env: { ...process.env, WRANGLER_SEND_METRICS: "false" } },
  );
  await waitForServer();
  log("worker ready");

  // 3) snapshot HTML routes
  for (const route of HTML_ROUTES) {
    const file = route === "/" ? "index.html" : `${route.replace(/^\//, "")}/index.html`;
    const size = await saveRoute(route, file);
    log(`  ${route} -> ${file} (${size} bytes)`);
  }
  // 4) snapshot text routes
  for (const [route, file] of TEXT_ROUTES) {
    try { const size = await saveRoute(route, file); log(`  ${route} -> ${file} (${size} bytes)`); }
    catch (e) { log(`  skip ${route}: ${e.message}`); }
  }

  log(`done. static site in ${outDir}`);
} finally {
  if (child) { try { child.kill("SIGTERM"); } catch { /* ignore */ } }
}
// ensure the process exits (wrangler child can keep the loop alive)
setTimeout(() => process.exit(0), 300);
